# Site
repository: kiranprasad2001/resume
favicon: /resume/images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kiran Prasad
title: DevOps and CCM Consultant
email: kiranprasad2001@gmail.com
website: https://spotrot.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: kiranprasad2001
github_username:  kiranprasad2001
# stackoverflow_username: "kiranprasad2001"
# dribbble_username: kiranprasad2001
# facebook_username: kiranprasad2001
# flickr_username: kiranprasad2001
instagram_username: kiranprasad2001
linkedin_username: kiranprasad2001
# xing_username: kiranprasad2001
# pinterest_username: kiranprasad2001
#youtube_username: kiranprasad2001
# googleplus_username: +kiranprasad2001
# orcid_username: kiranprasad2001
#testing

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/mylogo.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Kiran. I'm a Documaker and DevOps consultant. As well as administrating systems I also have experience making small web apps. I have worked at a number of companies gaining teamwork and leadership skills.
  I am most skilled in: <mark>AWS</mark>,<mark>Kubernites</mark>,<mark>Jenkins</mark> and <mark>Eating Biryani</mark>

content:
  - title: Skill Set
    layout: text
    content: |
      - Operating System     : <mark>Linux, Windows</mark>
      - Version Controls     : <mark>GIT</mark>
      - Configuration Management : <mark>Ansible</mark>
      - Build Tools          : <mark>Ant, Maven</mark>
      - CI Tools             : <mark>Jenkins, Gitlab CI</mark>
      - Containerization tool : <mark>Docker, Kubernites</mark>
      - Scripting            : <mark>Shell Scripting</mark>
      - Application Servers  : <mark>Tomcat, Web logic</mark>
      - Ticketing Tool       : <mark>JIRA, ALM</mark>
      - DevOps tools         : <mark>Puppet</mark>
      - Ticketing tools      : <mark>Jira</mark>
      - Incident tools       : <mark>BMC remedy</mark>
      - Artifactory Repos    : <mark>Nexus, jFrog</mark>
      - Logging tools        : <mark>Splunk, ELK Stack</mark>
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: My Resume
        #link: https://spotrot.com/resume/
        # link_text: Project Website
        additional_links:
          - title:  Resume
            icon: fab fa-github
            url: https://spotrot.com/resume/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Nothing much - under construction
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>webapps</mark> and in process of completing it
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cognizant
        link: cognizant.com
        # link_text: boringcompany.com
        sub_title: Senior Consultant
        caption: July' 16 - December' 20
        quote: >
          Solving 21st century problems by ensuring deployments are automated and issues are not popping up.
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: VRSEC, Vijayawada
        caption: 2008 - 2012
        sub_title: B. Tech - EIE
        quote: >
          V R Siddhartha is the oldest higher education institution in Andhra Pradesh, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the state but also in India.
        description: | # this will include new lines to allow paragraphs
          During my time at college, I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time at college and learnt a lot about a healthy work life balance.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in DevOps and CCM industry, some of my other interests and hobbies are:
      - Trekking
      - Backpacking
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
      - Look at this cool image  
      ![Lake](images/lake-kiran.jpg "Lake")
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag